# ------------------------------------------------------------------------------
# File: export_probe_feature_concordance_to_quarto.R
# Purpose: Export probe feature concordance tables and plots into Quarto resources.
# Role: Reporting resource exporter
# Pipeline: Reporting / Feature-space concordance
# Project: Global Cancer Complexity
# Author: Ali M. Al-Timimi
# Created: 2026
# ------------------------------------------------------------------------------

#' Export probe feature concordance outputs for Quarto rendering
#'
#' This helper takes the canonical concordance outputs generated by
#' generate_probe_feature_concordance() and writes/copies the Quarto-ready
#' resources used by results/probe_feature_space_concordance.qmd. It also copies
#' the annotation-ready probe-set membership table for later biological
#' annotation chapters.
#'
#' @param concordance_tbl Optional concordance table already in memory.
#' @param group_summary_tbl Optional group summary table already in memory.
#' @param chip Chip/platform name.
#' @param source_table_dir Directory containing canonical concordance tables.
#' @param source_plot_dir Directory containing canonical concordance plots.
#' @param quarto_table_dir Destination directory under quarto/resources/tables.
#' @param quarto_plot_dir Destination directory under quarto/resources/plots.
#' @param plot_utils_path Optional project plot utility path.
#' @return Invisibly returns a list of exported paths.
#' @export

export_probe_feature_concordance_to_quarto <- function(concordance_tbl = NULL,
                                                       group_summary_tbl = NULL,
                                                       chip = "hu35ksuba",
                                                       source_table_dir = "output/global_cancer/tables/probe_concordance",
                                                       source_plot_dir = "output/global_cancer/plots/probe_concordance",
                                                       quarto_table_dir = "quarto/resources/tables/probe_concordance",
                                                       quarto_plot_dir = "quarto/resources/plots/probe_concordance",
                                                       plot_utils_path = "R/helpers/plot_utils.R") {
  required_pkgs <- c("dplyr", "readr", "ggplot2", "stringr", "tibble", "forcats")
  missing_pkgs <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]
  if (length(missing_pkgs) > 0) {
    stop("Missing required packages: ",
         paste(missing_pkgs, collapse = ", "),
         call. = FALSE)
  }
  
  dir.create(quarto_table_dir,
             recursive = TRUE,
             showWarnings = FALSE)
  dir.create(quarto_plot_dir,
             recursive = TRUE,
             showWarnings = FALSE)
  
  if (!is.null(plot_utils_path) && file.exists(plot_utils_path)) {
    source(plot_utils_path)
  }
  
  save_plot <- function(plot,
                        path,
                        width = 8,
                        height = 6,
                        dpi = 300) {
    if (exists("save_png_light", mode = "function")) {
      save_png_light(plot,
                     path,
                     width = width,
                     height = height,
                     dpi = dpi)
    } else {
      ggplot2::ggsave(
        path,
        plot = plot,
        width = width,
        height = height,
        dpi = dpi,
        bg = "white"
      )
    }
  }
  
  group_palette <- c(
    blastomas  = "#CC79A7",
    carcinomas = "#D55E00",
    leukemias  = "#0072B2",
    lymphomas  = "#009E73"
  )
  
  clean_chip <- gsub("[^a-zA-Z0-9]", "_", tolower(chip))
  
  canonical_concordance_csv <- file.path(source_table_dir,
                                         paste0(clean_chip, "_top_features_vs_limma_concordance.csv"))
  
  canonical_group_csv <- file.path(
    source_table_dir,
    paste0(clean_chip, "_top_features_vs_limma_group_summary.csv")
  )
  
  canonical_probe_sets_long_csv <- file.path(
    source_table_dir,
    paste0(clean_chip, "_top_features_vs_limma_probe_sets_long.csv")
  )
  canonical_probe_sets_long_rds <- file.path(
    source_table_dir,
    paste0(clean_chip, "_top_features_vs_limma_probe_sets_long.rds")
  )
  
  if (is.null(concordance_tbl)) {
    if (!file.exists(canonical_concordance_csv)) {
      stop("Canonical concordance table not found: ",
           canonical_concordance_csv,
           call. = FALSE)
    }
    concordance_tbl <- readr::read_csv(canonical_concordance_csv, show_col_types = FALSE)
  } else {
    concordance_tbl <- tibble::as_tibble(concordance_tbl)
  }
  
  if (is.null(group_summary_tbl)) {
    if (file.exists(canonical_group_csv)) {
      group_summary_tbl <- readr::read_csv(canonical_group_csv, show_col_types = FALSE)
    }
  } else {
    group_summary_tbl <- tibble::as_tibble(group_summary_tbl)
  }
  
  # Backward compatibility for earlier column names.
  if (!"overlap_frac_of_top3000" %in% names(concordance_tbl) &&
      "overlap_frac_of_top_features" %in% names(concordance_tbl)) {
    concordance_tbl <- concordance_tbl |>
      dplyr::rename(overlap_frac_of_top3000 = .data$overlap_frac_of_top_features)
  }
  
  required_cols <- c(
    "chip",
    "group",
    "comparison",
    "limma_n",
    "top_feature_n",
    "overlap_n",
    "overlap_frac_of_limma",
    "overlap_frac_of_top3000"
  )
  
  missing_cols <- setdiff(required_cols, names(concordance_tbl))
  if (length(missing_cols) > 0) {
    stop(
      "Concordance table is missing required columns: ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }
  
  preferred_cols <- c(
    "chip",
    "group",
    "comparison",
    "limma_n",
    "top_feature_n",
    "overlap_n",
    "non_overlap_limma",
    "non_overlap_top3000",
    "overlap_frac_of_limma",
    "overlap_frac_of_top3000",
    "universe_n",
    "universe_source",
    "expected_overlap",
    "fold_enrichment",
    "hypergeom_p",
    "hypergeom_fdr"
  )
  
  concordance_export <- concordance_tbl |>
    dplyr::select(dplyr::any_of(preferred_cols), dplyr::everything()) |>
    dplyr::arrange(.data$group,
                   dplyr::desc(.data$overlap_frac_of_limma),
                   .data$comparison)
  
  concordance_resource_csv <- file.path(quarto_table_dir,
                                        paste0(clean_chip, "_probe_feature_concordance.csv"))
  concordance_resource_rds <- file.path(quarto_table_dir,
                                        paste0(clean_chip, "_probe_feature_concordance.rds"))
  
  readr::write_csv(concordance_export, concordance_resource_csv)
  saveRDS(concordance_export, concordance_resource_rds)
  
  exported_paths <- list(concordance_csv = concordance_resource_csv, concordance_rds = concordance_resource_rds)
  
  if (!is.null(group_summary_tbl)) {
    if (!"median_overlap_frac_of_top3000" %in% names(group_summary_tbl) &&
        "median_overlap_frac_of_top_features" %in% names(group_summary_tbl)) {
      group_summary_tbl <- group_summary_tbl |>
        dplyr::rename(median_overlap_frac_of_top3000 = .data$median_overlap_frac_of_top_features)
    }
    
    group_resource_csv <- file.path(
      quarto_table_dir,
      paste0(
        clean_chip,
        "_probe_feature_concordance_group_summary.csv"
      )
    )
    group_resource_rds <- file.path(
      quarto_table_dir,
      paste0(
        clean_chip,
        "_probe_feature_concordance_group_summary.rds"
      )
    )
    
    readr::write_csv(group_summary_tbl, group_resource_csv)
    saveRDS(group_summary_tbl, group_resource_rds)
    
    exported_paths$group_summary_csv <- group_resource_csv
    exported_paths$group_summary_rds <- group_resource_rds
  }
  
  # Copy annotation-ready probe-set membership resources when available.
  if (file.exists(canonical_probe_sets_long_csv)) {
    probe_sets_resource_csv <- file.path(
      quarto_table_dir,
      paste0(clean_chip, "_probe_feature_set_membership_long.csv")
    )
    file.copy(canonical_probe_sets_long_csv,
              probe_sets_resource_csv,
              overwrite = TRUE)
    exported_paths$probe_sets_long_csv <- probe_sets_resource_csv
  }
  
  if (file.exists(canonical_probe_sets_long_rds)) {
    probe_sets_resource_rds <- file.path(
      quarto_table_dir,
      paste0(clean_chip, "_probe_feature_set_membership_long.rds")
    )
    file.copy(canonical_probe_sets_long_rds,
              probe_sets_resource_rds,
              overwrite = TRUE)
    exported_paths$probe_sets_long_rds <- probe_sets_resource_rds
  }
  
  # ---- Primary QMD plot: coverage vs occupancy ----
  plot_tbl <- concordance_export |>
    dplyr::mutate(comparison_label = stringr::str_wrap(.data$comparison, width = 24))
  
  p_scatter <- ggplot2::ggplot(
    plot_tbl,
    ggplot2::aes(
      x = .data$overlap_frac_of_limma,
      y = .data$overlap_frac_of_top3000,
      size = .data$limma_n,
      color = .data$group
    )
  ) +
    ggplot2::geom_point(shape = 16, alpha = 0.85) +
    ggplot2::scale_color_manual(values = group_palette, drop = FALSE) +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = paste0(chip, ": limma coverage versus latent feature-space occupancy"),
      x = "Fraction of limma-filtered probes represented in top-3000 latent features",
      y = "Fraction of top-3000 latent features represented by limma probes",
      size = "Limma probes",
      color = "Cancer group"
    )
  
  if (requireNamespace("ggrepel", quietly = TRUE)) {
    p_scatter <- p_scatter +
      ggrepel::geom_text_repel(
        ggplot2::aes(label = .data$comparison),
        size = 3,
        max.overlaps = Inf,
        show.legend = FALSE
      )
  } else {
    p_scatter <- p_scatter +
      ggplot2::geom_text(
        ggplot2::aes(label = .data$comparison),
        size = 3,
        vjust = -0.8,
        check_overlap = TRUE,
        show.legend = FALSE
      )
  }
  
  scatter_path <- file.path(
    quarto_plot_dir,
    paste0(
      clean_chip,
      "_probe_concordance_coverage_vs_occupancy.png"
    )
  )
  save_plot(p_scatter,
            scatter_path,
            width = 9,
            height = 6)
  exported_paths$coverage_vs_occupancy_plot <- scatter_path
  
  # ---- Secondary QMD plot: limma coverage by comparison ----
  p_coverage <- ggplot2::ggplot(
    plot_tbl,
    ggplot2::aes(
      x = forcats::fct_reorder(
        .data$comparison_label,
        .data$overlap_frac_of_limma,
        .desc = TRUE
      ),
      y = .data$overlap_frac_of_limma,
      fill = .data$group
    )
  ) +
    ggplot2::geom_col() +
    ggplot2::coord_flip() +
    ggplot2::scale_fill_manual(values = group_palette, drop = FALSE) +
    ggplot2::theme_minimal() +
    ggplot2::labs(
      title = paste0(chip, ": limma-filtered probe coverage by latent top-3000 features"),
      x = NULL,
      y = "Overlap fraction of limma-filtered probes",
      fill = "Cancer group"
    )
  
    coverage_path <- file.path(quarto_plot_dir,
                             paste0(clean_chip, "_probe_concordance_limma_coverage.png"))
  save_plot(p_coverage,
            coverage_path,
            width = 10,
            height = max(5, 0.35 * nrow(plot_tbl)))
  exported_paths$limma_coverage_plot <- coverage_path
  
  # Copy existing canonical plots, if present, as supplemental resources.
  canonical_plot_files <- c(
    paste0(clean_chip, "_top_features_vs_limma_overlap_fraction.png"),
    paste0(clean_chip, "_top_features_vs_limma_fold_enrichment.png"),
    paste0(clean_chip, "_top_features_vs_limma_group_summary.png")
  )
  
  for (plot_file in canonical_plot_files) {
    src <- file.path(source_plot_dir, plot_file)
    if (file.exists(src)) {
      dest <- file.path(quarto_plot_dir, plot_file)
      file.copy(src, dest, overwrite = TRUE)
      exported_paths[[paste0("copied_", tools::file_path_sans_ext(plot_file))]] <- dest
    }
  }
  
  message("Wrote Quarto concordance table: ", concordance_resource_csv)
  if (!is.null(exported_paths$group_summary_csv)) {
    message("Wrote Quarto group summary table: ",
            exported_paths$group_summary_csv)
  }
  if (!is.null(exported_paths$probe_sets_long_csv)) {
    message("Wrote Quarto probe-set membership table: ",
            exported_paths$probe_sets_long_csv)
  }
  message("Wrote Quarto concordance plot: ", scatter_path)
  message("Wrote Quarto coverage plot: ", coverage_path)
  
  invisible(exported_paths)
}
