from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd

from .latent_config import REQUIRED_METADATA_COLUMNS, MINIMAL_METADATA_COLUMNS


def load_expression(expression_path: Path) -> pd.DataFrame:
    """Load expression matrix as samples x features, indexed by sample_id."""
    if not expression_path.exists():
        raise FileNotFoundError(f"Expression file not found: {expression_path}")
    expression = pd.read_csv(expression_path, index_col=0)
    expression.index = expression.index.astype(str)
    expression.index.name = "sample_id"
    return expression


def load_metadata(
    metadata_path: Path,
    require_full_contract: bool = True,
) -> pd.DataFrame:
    """Load metadata while preserving sample_id as both index and column."""
    if not metadata_path.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    metadata = pd.read_csv(metadata_path)

    if "sample_id" not in metadata.columns:
        raise ValueError(
            "Metadata is missing 'sample_id'. "
            "Check the R export and avoid reading metadata with index_col=0 before saving."
        )

    metadata["sample_id"] = metadata["sample_id"].astype(str)
    metadata = metadata.set_index("sample_id", drop=False)

    required = REQUIRED_METADATA_COLUMNS if require_full_contract else MINIMAL_METADATA_COLUMNS
    missing = [c for c in required if c not in metadata.columns]
    if missing:
        raise ValueError(f"Missing required metadata columns: {missing}")

    return metadata


def validate_expression_metadata_alignment(
    expression: pd.DataFrame,
    metadata: pd.DataFrame,
) -> None:
    """Ensure expression rows and metadata rows are exactly aligned by sample_id."""
    if expression.shape[0] != metadata.shape[0]:
        raise ValueError(
            f"Sample count mismatch: expression has {expression.shape[0]}, "
            f"metadata has {metadata.shape[0]}"
        )

    if set(expression.index) != set(metadata.index):
        expression_only = sorted(set(expression.index) - set(metadata.index))[:10]
        metadata_only = sorted(set(metadata.index) - set(expression.index))[:10]
        raise ValueError(
            "Expression and metadata do not contain the same sample IDs. "
            f"expression-only examples={expression_only}; metadata-only examples={metadata_only}"
        )

    if not expression.index.equals(metadata.index):
        first_bad = next(
            (i for i, (a, b) in enumerate(zip(expression.index, metadata.index)) if a != b),
            None,
        )
        raise ValueError(
            "Expression and metadata indices are not identically ordered. "
            f"First mismatch at position {first_bad}: "
            f"{expression.index[first_bad]} != {metadata.index[first_bad]}"
        )

    sample_id_matches_index = metadata["sample_id"].astype(str).equals(
        metadata.index.to_series().astype(str)
    )
    if not sample_id_matches_index:
        raise ValueError("sample_id column does not match metadata index.")


def validate_numeric_expression(expression: pd.DataFrame) -> None:
    """Ensure the expression matrix contains only numeric feature columns."""
    non_numeric_cols = expression.columns[expression.dtypes == "object"].tolist()
    if non_numeric_cols:
        raise TypeError(
            "Expression matrix contains non-numeric columns. "
            f"First examples: {non_numeric_cols[:10]}"
        )


def load_ml_inputs(config, require_full_contract: bool = True):
    """Load expression and metadata according to a LatentConfig."""
    expression = load_expression(config.expression_path)
    metadata = load_metadata(config.metadata_path, require_full_contract=require_full_contract)
    validate_expression_metadata_alignment(expression, metadata)
    validate_numeric_expression(expression)
    return expression, metadata


def load_feature_table(features_path: Path) -> pd.DataFrame:
    """Load feature table generated by the R preprocessing pipeline."""
    if not features_path.exists():
        raise FileNotFoundError(f"Feature table not found: {features_path}")
    return pd.read_csv(features_path)


def load_latent_array(latent_path: Path) -> np.ndarray:
    """Load latent coordinate matrix."""
    if not latent_path.exists():
        raise FileNotFoundError(f"Latent file not found: {latent_path}")
    return np.load(latent_path)
